"""
knowledgegraph.py — Manara Semantic Knowledge Graph
====================================================

This module is the single source of truth for all graph-based intelligence
in Manara.  It owns:

  • Building the RDF/OWL graph from course data files
  • Serialising to Turtle (.ttl)
  • Loading the graph with a module-level cache (parsed once per process)
  • Prerequisite BFS traversal (secondary metadata — NOT primary intelligence)
  • Cross-course semantic edge injection (from related_subtopics.csv)
  • Frontend-ready payload generation (for InsideManarasBrainPage)
  • Query helpers used by api_server.py

Architecture rules
──────────────────
1.  The graph is parsed from disk ONCE per process and cached in _GRAPH_CACHE.
    Every public function that needs the graph calls _get_graph(), which
    returns the cached instance.  Disk reads happen only on first call or
    after rebuild.

2.  build_knowledge_graph() is the only function that writes to disk.
    It must be called manually (python knowledgegraph.py) or via the
    /api/graph/rebuild endpoint after course data changes.

3.  No fake/demo/fallback data is generated by this module.  If the .ttl
    file does not exist, callers receive an empty result and a clear error
    message telling them to run the build.

4.  All public functions are safe to call from FastAPI route handlers and
    from background threads.

5.  Topic URIs include a per-course prefix AND the topic index to prevent
    collisions between same-named topics in different courses:
        topic/<safe_course>_<safe_topic>_<index>

6.  Subtopic URIs include the course prefix to prevent global collisions:
        subtopic/<safe_course>_<safe_subtopic>

7.  Cross-course semantic edges are injected from related_subtopics.csv at
    build time.  Two edge types are supported, auto-detected from CSV columns:

      NEW (preferred): source_subtopic / target_subtopic columns present
        → manara:isSemanticallySimilarTo edges between Subtopic nodes

      LEGACY: only source_topic / target_topic columns present
        → manara:isRelatedTo edges between Topic nodes (backward-compat)

    Both edge types are symmetric (A→B and B→A both stored).
    Only pairs with ChromaDB distance <= SIMILARITY_THRESHOLD are included.

8.  Manara's primary intelligence is semantic similarity across ALL courses
    globally, driven by SUBTOPIC-granularity isSemanticallySimilarTo edges.
    Prerequisites are metadata only — they are NOT used as the primary
    driver of diagnostic sampling or learning path ordering.
"""

from __future__ import annotations

import csv
import json
import os
import re
import threading
from collections import Counter, defaultdict
from pathlib import Path
from typing import Optional

from rdflib import Graph, Namespace, RDF, RDFS, OWL, Literal, URIRef


# =============================================================================
# CONFIG
# =============================================================================

PROJECT_DIR = Path(os.environ.get(
    "MANARA_PROJECT_DIR",
    "/Users/dinaal-memah/Desktop/graduation project 2",
))
COURSES_DIR = PROJECT_DIR / "courses"
OUTPUT_FILE = PROJECT_DIR / "course_knowledge_graph.ttl"
RELATED_CSV = PROJECT_DIR / "related_subtopics.csv"

BASE_URI = "http://manara.org/kg/"
EX       = Namespace(BASE_URI)
MANARA   = Namespace(BASE_URI + "ontology/")

# Only cross-course similarity edges with distance <= this are stored.
SIMILARITY_THRESHOLD: float = 0.5

# Frontend payload size caps — prevents sending multi-MB JSON to the browser.
# App.jsx trims further client-side, but trimming server-side first is faster.
FRONTEND_MAX_COURSE_NODES: int = 40
FRONTEND_MAX_TOPIC_NODES:  int = 40
FRONTEND_MAX_EDGES:        int = 600

COURSE_SEMANTIC_EDGE_LIMIT: int = 220
COURSE_SEMANTIC_MIN_LINKS:  int = 1

FOUNDATIONAL_RELATIONSHIPS: list[dict] = [
    {
        "source_course": "Structured Programming",
        "target_course": "Object Oriented Programming",
        "label": "isFoundationalFor",
        "relationship": "foundational",
        "strength": 0.95,
        "link_count": 1,
        "shared_concepts": ["programming fundamentals", "control flow", "functions", "data representation"],
        "explanation": "Structured Programming is foundational for Object Oriented Programming because OOP extends procedural control flow, functions, data representation, and modular design.",
    },
    {
        "source_course": "Data Structures and Introduction to Algorithms",
        "target_course": "Algorithms Design and Analysis",
        "label": "isFoundationalFor",
        "relationship": "foundational",
        "strength": 1.0,
        "link_count": 1,
        "shared_concepts": ["arrays", "linked structures", "trees", "graphs", "algorithmic complexity"],
        "explanation": "Data Structures is foundational for Algorithms because algorithm design depends on arrays, linked structures, trees, graphs, and complexity analysis.",
    },
    {
        "source_course": "Calculus (1)",
        "target_course": "Calculus (2)",
        "label": "isFoundationalFor",
        "relationship": "foundational",
        "strength": 1.0,
        "link_count": 1,
        "shared_concepts": ["limits", "derivatives", "integrals", "series"],
        "explanation": "Calculus (1) is foundational for Calculus (2) because integration techniques and series build on limits, derivatives, and basic integrals.",
    },
    {
        "source_course": "Statistical Methods",
        "target_course": "Introduction to Data Science",
        "label": "isFoundationalFor",
        "relationship": "foundational",
        "strength": 0.9,
        "link_count": 1,
        "shared_concepts": ["probability", "statistics", "inference", "data analysis"],
        "explanation": "Statistical Methods is foundational for Data Science because data modeling relies on probability, statistical inference, and analysis methods.",
    },
    {
        "source_course": "Artificial Intelligence",
        "target_course": "Natural Language Processing",
        "label": "extendsConceptsFrom",
        "relationship": "foundational",
        "strength": 0.82,
        "link_count": 1,
        "shared_concepts": ["search", "language models", "classification", "reasoning"],
        "explanation": "Natural Language Processing extends Artificial Intelligence through search, classification, reasoning, and language-modeling methods.",
    },
]


# =============================================================================
# MODULE-LEVEL GRAPH CACHE
# =============================================================================
# The graph is parsed once and kept in memory for the lifetime of the process.
# _GRAPH_LOCK serialises concurrent first-load requests.
# Cache is invalidated automatically when the .ttl file mtime changes.

_GRAPH_CACHE: dict = {"graph": None, "mtime": 0.0}
_GRAPH_LOCK  = threading.Lock()


def _get_graph() -> Optional[Graph]:
    """
    Return the cached rdflib.Graph, loading from disk if needed.

    Returns None when the .ttl file does not exist so callers handle
    a missing graph gracefully without crashing the API.
    Cache is invalidated automatically when the file is rebuilt.
    """
    if not OUTPUT_FILE.exists():
        return None

    current_mtime = OUTPUT_FILE.stat().st_mtime

    with _GRAPH_LOCK:
        cached = _GRAPH_CACHE["graph"]
        if cached is not None and _GRAPH_CACHE["mtime"] == current_mtime:
            return cached  # fast path — already loaded, file unchanged

        g = Graph()
        g.parse(str(OUTPUT_FILE), format="turtle")
        _GRAPH_CACHE["graph"] = g
        _GRAPH_CACHE["mtime"] = current_mtime
        print(f"[KG] Graph loaded from disk — {len(g)} triples.")
        return g


def invalidate_graph_cache() -> None:
    """Force the next _get_graph() call to re-read from disk (after rebuild)."""
    with _GRAPH_LOCK:
        _GRAPH_CACHE["graph"] = None
        _GRAPH_CACHE["mtime"] = 0.0


# =============================================================================
# HELPERS
# =============================================================================

def safe_id(text: str) -> str:
    """Slug a string to a URI-safe identifier."""
    return re.sub(r"[^a-zA-Z0-9_]+", "_", text.strip().lower()).strip("_")


def make_uri(entity_type: str, identifier: str) -> URIRef:
    return EX[f"{entity_type}/{safe_id(identifier)}"]


def get_course_folders(courses_dir: Path) -> list[Path]:
    if not courses_dir.exists():
        return []
    return sorted([p for p in courses_dir.iterdir() if p.is_dir()])


def _load_json(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def _name_lookup(g: Graph) -> dict[str, str]:
    """Build {uri_str -> human_name} from every manara:name triple."""
    return {
        str(subj): str(obj).strip()
        for subj, pred, obj in g
        if str(pred) == str(MANARA.name) and isinstance(obj, Literal)
    }


def _detect_node_type(node_id: str) -> str:
    """Return 'course', 'topic', or 'hidden' for a URI path segment."""
    low = node_id.lower()
    if low.startswith("course/"):
        return "course"
    if low.startswith("topic/") or low.startswith("subtopic/"):
        return "topic"
    return "hidden"


def _find_course_uri(g: Graph, course_name: str) -> Optional[URIRef]:
    """Look up a course URIRef by stored manara:name, with slug fallback."""
    for subj, _, _ in g.triples((None, MANARA.name, Literal(course_name))):
        if (subj, RDF.type, MANARA.Course) in g:
            return subj
    # Slug fallback for minor capitalisation/spacing differences
    candidate = EX[f"course/{safe_id(course_name)}"]
    if (candidate, RDF.type, MANARA.Course) in g:
        return candidate
    return None


def _course_desc_lookup(g: Graph, names: dict[str, str]) -> dict[str, str]:
    """
    Build {course_uri_str -> description} from courseCode + prerequisite names.
    Example: "Code: 14260 | Requires: Introduction to Data Science"
    """
    desc: dict[str, str] = {}
    for subj, _, obj in g.triples((None, MANARA.courseCode, None)):
        code  = str(obj)
        parts = [f"Code: {code}"]
        prereqs = [
            names.get(str(o), str(o).split("/")[-1].replace("_", " "))
            for _, _, o in g.triples((subj, MANARA.hasPrerequisite, None))
        ]
        if prereqs:
            parts.append("Requires: " + ", ".join(prereqs))
        desc[str(subj)] = " | ".join(parts)
    return desc


# =============================================================================
# SCHEMA DEFINITION
# =============================================================================

def _add_schema(g: Graph) -> None:
    g.bind("ex",     EX)
    g.bind("manara", MANARA)
    g.bind("rdf",    RDF)
    g.bind("rdfs",   RDFS)
    g.bind("owl",    OWL)

    for cls in ("Course", "Material", "Topic", "Subtopic", "Keyword"):
        g.add((MANARA[cls], RDF.type,   OWL.Class))
        g.add((MANARA[cls], RDFS.label, Literal(cls)))

    object_props = {
        "hasPrerequisite":        ("Course",   "Course"),
        "hasConcurrent":          ("Course",   "Course"),
        "hasMaterial":            ("Course",   "Material"),
        "hasTopic":               ("Course",   "Topic"),
        "coversTopic":            ("Material", "Topic"),
        "hasSubtopic":            ("Topic",    "Subtopic"),
        "hasKeyword":             ("Topic",    "Keyword"),
        "isRelatedTo":            ("Topic",    "Topic"),    # legacy cross-course topic edge
        "isSemanticallySimilarTo": ("Subtopic", "Subtopic"), # new cross-course subtopic edge
        "isSemanticallyRelatedTo": ("Course",   "Course"),   # aggregated semantic course edge
        "sharesMathematicsWith":   ("Course",   "Course"),
        "sharesMethodsWith":       ("Course",   "Course"),
        "isFoundationalFor":       ("Course",   "Course"),
        "extendsConceptsFrom":     ("Course",   "Course"),
    }
    for prop, (domain, rng) in object_props.items():
        g.add((MANARA[prop], RDF.type,    OWL.ObjectProperty))
        g.add((MANARA[prop], RDFS.domain, MANARA[domain]))
        g.add((MANARA[prop], RDFS.range,  MANARA[rng]))
        g.add((MANARA[prop], RDFS.label,  Literal(prop)))

    for prop in ("name", "courseCode", "chapter", "fileName",
                 "relativePath", "fileType", "similarityScore",
                 "relationshipStrength", "relationshipExplanation",
                 "sharedConcepts", "semanticLinkCount"):
        g.add((MANARA[prop], RDF.type,   OWL.DatatypeProperty))
        g.add((MANARA[prop], RDFS.label, Literal(prop)))


# =============================================================================
# GRAPH BUILDING
# =============================================================================

def build_knowledge_graph(courses_dir: Path = COURSES_DIR) -> Graph:
    """
    Build the full RDF graph from all course data files and return it.

    Data sources (in order):
      1. courses/<name>/metadata/prerequisites.json   -> Course nodes + prereq edges
      2. courses/<name>/metadata/materials_index.json -> Material nodes
      3. courses/<name>/outputs/chapter_concepts.json -> Topic + Subtopic nodes
      4. related_subtopics.csv (project root)          -> isRelatedTo edges

    rdflib.Graph uses a set internally so adding the same triple twice is a
    no-op — duplicate nodes and edges cannot appear.

    URI collision prevention:
      - Topic URIs   = topic/<course_slug>_<topic_slug>_<index>
      - Subtopic URIs = subtopic/<course_slug>_<subtopic_slug>
    """
    g = Graph()
    _add_schema(g)

    # (course_name, topic_name)    -> URIRef  — for isRelatedTo (legacy) edge injection
    topic_uri_map: dict[tuple[str, str], URIRef] = {}
    # (course_name, subtopic_name) -> URIRef  — for isSemanticallySimilarTo edge injection
    subtopic_uri_map: dict[tuple[str, str], URIRef] = {}

    for course_dir in get_course_folders(courses_dir):
        course_name  = course_dir.name
        metadata_dir = course_dir / "metadata"
        outputs_dir  = course_dir / "outputs"

        course_uri = make_uri("course", course_name)
        g.add((course_uri, RDF.type,    MANARA.Course))
        g.add((course_uri, MANARA.name, Literal(course_name)))
        g.add((course_uri, RDFS.label,  Literal(course_name)))

        # -- Prerequisites -------------------------------------------------
        prereq_file = metadata_dir / "prerequisites.json"
        if prereq_file.exists():
            try:
                prereq_data = _load_json(prereq_file)
            except Exception as e:
                print(f"[KG] Bad prerequisites.json for {course_name}: {e}")
                prereq_data = {}

            code = prereq_data.get("course_code", "")
            if code:
                g.add((course_uri, MANARA.courseCode, Literal(str(code))))

            for prereq in prereq_data.get("prerequisites", []):
                prereq = str(prereq).strip()
                if not prereq:
                    continue
                prereq_uri = make_uri("course", prereq)
                g.add((prereq_uri, RDF.type,    MANARA.Course))
                g.add((prereq_uri, MANARA.name, Literal(prereq)))
                g.add((prereq_uri, RDFS.label,  Literal(prereq)))
                g.add((course_uri, MANARA.hasPrerequisite, prereq_uri))

            for concurrent in prereq_data.get("concurrent", []):
                concurrent = str(concurrent).strip()
                if not concurrent:
                    continue
                conc_uri = make_uri("course", concurrent)
                g.add((conc_uri,   RDF.type,    MANARA.Course))
                g.add((conc_uri,   MANARA.name, Literal(concurrent)))
                g.add((conc_uri,   RDFS.label,  Literal(concurrent)))
                g.add((course_uri, MANARA.hasConcurrent, conc_uri))

        # -- Materials -----------------------------------------------------
        materials_map: dict[str, URIRef] = {}
        mat_file = metadata_dir / "materials_index.json"
        if mat_file.exists():
            try:
                mat_data = _load_json(mat_file)
            except Exception as e:
                print(f"[KG] Bad materials_index.json for {course_name}: {e}")
                mat_data = {}

            for mat in mat_data.get("materials", []):
                rel_path  = str(mat.get("relative_path", "")).strip()
                mat_id    = mat.get("material_id") or safe_id(rel_path) or safe_id(course_name + "_mat")
                mat_uri   = make_uri("material", mat_id)
                file_name = str(mat.get("file_name", mat_id))

                materials_map[rel_path] = mat_uri
                g.add((mat_uri,    RDF.type,            MANARA.Material))
                g.add((mat_uri,    RDFS.label,          Literal(file_name)))
                g.add((mat_uri,    MANARA.fileName,     Literal(file_name)))
                g.add((mat_uri,    MANARA.relativePath, Literal(rel_path)))
                g.add((mat_uri,    MANARA.fileType,     Literal(str(mat.get("file_type", "")))))
                g.add((mat_uri,    MANARA.chapter,      Literal(str(mat.get("chapter", "")))))
                g.add((course_uri, MANARA.hasMaterial,  mat_uri))

        # -- Topics & Subtopics -------------------------------------------
        concepts_file = outputs_dir / "chapter_concepts.json"
        if concepts_file.exists():
            try:
                concepts_data = _load_json(concepts_file)
            except Exception as e:
                print(f"[KG] Bad chapter_concepts.json for {course_name}: {e}")
                concepts_data = {}

            for relative_path, content in concepts_data.items():
                chapter     = str(content.get("chapter", "")).strip()
                mat_uri_ref = materials_map.get(relative_path)

                for topic_index, topic in enumerate(content.get("topics", [])):
                    topic_name = str(topic.get("topic_name", "")).strip()
                    if not topic_name:
                        continue

                    # Include course + index to prevent cross-course URI collisions
                    topic_uri = make_uri(
                        "topic",
                        f"{course_name}_{topic_name}_{topic_index}",
                    )

                    g.add((topic_uri,  RDF.type,       MANARA.Topic))
                    g.add((topic_uri,  MANARA.name,    Literal(topic_name)))
                    g.add((topic_uri,  MANARA.chapter, Literal(chapter)))
                    g.add((topic_uri,  RDFS.label,     Literal(topic_name)))
                    g.add((course_uri, MANARA.hasTopic, topic_uri))

                    if mat_uri_ref is not None:
                        g.add((mat_uri_ref, MANARA.coversTopic, topic_uri))

                    # Register for cross-course edge injection.
                    # If the same topic_name appears in multiple chapters of the
                    # same course, last URI wins — acceptable for lookup.
                    topic_uri_map[(course_name, topic_name)] = topic_uri

                    for subtopic in topic.get("subtopics", []):
                        subtopic = str(subtopic).strip()
                        if not subtopic:
                            continue
                        sub_uri = make_uri("subtopic", f"{course_name}_{subtopic}")
                        g.add((sub_uri,   RDF.type,          MANARA.Subtopic))
                        g.add((sub_uri,   MANARA.name,       Literal(subtopic)))
                        g.add((sub_uri,   RDFS.label,        Literal(subtopic)))
                        g.add((topic_uri, MANARA.hasSubtopic, sub_uri))

                        # Register for cross-course subtopic edge injection.
                        # If the same subtopic_name appears in multiple topics of
                        # the same course, last URI wins — acceptable for lookup.
                        subtopic_uri_map[(course_name, subtopic)] = sub_uri

                    for keyword in topic.get("keywords", []):
                        keyword = str(keyword).strip()
                        if not keyword:
                            continue
                        kw_uri = make_uri("keyword", keyword)
                        g.add((kw_uri,    RDF.type,         MANARA.Keyword))
                        g.add((kw_uri,    MANARA.name,      Literal(keyword)))
                        g.add((kw_uri,    RDFS.label,       Literal(keyword)))
                        g.add((topic_uri, MANARA.hasKeyword, kw_uri))

    # -- Cross-course semantic edges ---------------------------------------
    _inject_related_topic_edges(g, topic_uri_map, subtopic_uri_map)
    _inject_course_semantic_edges(g)
    _inject_foundational_course_edges(g)

    return g


def _inject_related_topic_edges(
    g:               Graph,
    topic_uri_map:   dict[tuple[str, str], URIRef],
    subtopic_uri_map: dict[tuple[str, str], URIRef],
) -> None:
    """
    Read related_subtopics.csv and add bidirectional semantic edges between
    nodes from DIFFERENT courses whose distance <= SIMILARITY_THRESHOLD.

    Auto-detects CSV format from column headers:

      NEW format (subtopic-level — preferred):
        Columns: source_course, source_topic, source_subtopic,
                 target_course, target_topic, target_subtopic, distance
        → injects manara:isSemanticallySimilarTo between Subtopic URIs

      LEGACY format (topic-level — backward-compatible):
        Columns: source_course, source_topic, target_course, target_topic, distance
        → injects manara:isRelatedTo between Topic URIs

    Skips silently if the CSV is missing.
    Deduplicates within each edge type using a sorted-pair set.
    """
    if not RELATED_CSV.exists():
        print("[KG] related_subtopics.csv not found — no cross-course edges added.")
        print("     Run related_subtopic_analysis.py to generate it.")
        return

    subtopic_added: set[tuple[str, str]] = set()
    topic_added:    set[tuple[str, str]] = set()
    subtopic_edge_count = 0
    topic_edge_count    = 0
    skip_count          = 0

    try:
        with open(RELATED_CSV, "r", encoding="utf-8-sig", newline="") as f:
            reader    = csv.DictReader(f)
            fieldnames = [fn.strip() for fn in (reader.fieldnames or [])]

            # Detect which mode to run based on column presence
            has_subtopic_cols = (
                "source_subtopic" in fieldnames
                and "target_subtopic" in fieldnames
            )

            if has_subtopic_cols:
                print("[KG] Detected NEW subtopic-level CSV — injecting "
                      "isSemanticallySimilarTo edges.")
            else:
                print("[KG] Detected LEGACY topic-level CSV — injecting "
                      "isRelatedTo edges (run related_subtopic_analysis.py "
                      "to upgrade to subtopic-level).")

            for row in reader:
                src_course = str(row.get("source_course", "")).strip()
                tgt_course = str(row.get("target_course", "")).strip()
                dist_str   = str(row.get("distance", "1")).strip()

                if src_course == tgt_course:
                    continue

                try:
                    distance = float(dist_str)
                except ValueError:
                    continue

                if distance > SIMILARITY_THRESHOLD:
                    continue

                if has_subtopic_cols:
                    # ---- NEW: Subtopic ↔ Subtopic edges ------------------
                    src_sub = str(row.get("source_subtopic", "")).strip()
                    tgt_sub = str(row.get("target_subtopic", "")).strip()

                    if not src_sub or not tgt_sub:
                        skip_count += 1
                        continue

                    src_uri = subtopic_uri_map.get((src_course, src_sub))
                    tgt_uri = subtopic_uri_map.get((tgt_course, tgt_sub))

                    if src_uri is None or tgt_uri is None:
                        skip_count += 1
                        continue

                    pair = tuple(sorted([str(src_uri), str(tgt_uri)]))
                    if pair in subtopic_added:
                        continue
                    subtopic_added.add(pair)

                    g.add((src_uri, MANARA.isSemanticallySimilarTo, tgt_uri))
                    g.add((tgt_uri, MANARA.isSemanticallySimilarTo, src_uri))
                    subtopic_edge_count += 1

                else:
                    # ---- LEGACY: Topic ↔ Topic edges ---------------------
                    src_topic = str(row.get("source_topic", "")).strip()
                    tgt_topic = str(row.get("target_topic", "")).strip()

                    if not src_topic or not tgt_topic:
                        skip_count += 1
                        continue

                    src_uri = topic_uri_map.get((src_course, src_topic))
                    tgt_uri = topic_uri_map.get((tgt_course, tgt_topic))

                    if src_uri is None or tgt_uri is None:
                        skip_count += 1
                        continue

                    pair = tuple(sorted([str(src_uri), str(tgt_uri)]))
                    if pair in topic_added:
                        continue
                    topic_added.add(pair)

                    g.add((src_uri, MANARA.isRelatedTo, tgt_uri))
                    g.add((tgt_uri, MANARA.isRelatedTo, src_uri))
                    topic_edge_count += 1

    except Exception as e:
        print(f"[KG] Error reading related_subtopics.csv: {e}")
        return

    if subtopic_edge_count:
        print(f"[KG] Added {subtopic_edge_count} isSemanticallySimilarTo subtopic edges "
              f"(distance <= {SIMILARITY_THRESHOLD}, {skip_count} skipped).")
    if topic_edge_count:
        print(f"[KG] Added {topic_edge_count} isRelatedTo topic edges "
              f"(distance <= {SIMILARITY_THRESHOLD}, {skip_count} skipped).")


def _classify_course_relationship(terms: list[str]) -> str:
    text = " ".join(terms).lower()
    math_markers = {
        "matrix", "vector", "linear", "calculus", "probability", "statistics",
        "regression", "optimization", "gradient", "formula", "equation",
        "distance", "similarity", "entropy", "likelihood",
    }
    method_markers = {
        "algorithm", "ranking", "retrieval", "classification", "clustering",
        "search", "index", "embedding", "vector", "pipeline", "query",
        "graph", "tree", "model", "mining", "engineering",
    }
    if any(marker in text for marker in math_markers):
        return "mathematical"
    if any(marker in text for marker in method_markers):
        return "shared_methods"
    return "semantic"


def _edge_explanation(src_course: str, tgt_course: str, terms: list[str], link_count: int) -> str:
    clean_terms = []
    seen = set()
    for term in terms:
        term = str(term).strip()
        key = term.lower()
        if term and key not in seen:
            seen.add(key)
            clean_terms.append(term)
        if len(clean_terms) >= 5:
            break

    concept_text = ", ".join(clean_terms) if clean_terms else "closely related concepts"
    return (
        f"Connected because {src_course} and {tgt_course} share {concept_text}. "
        f"This course-level edge aggregates {link_count} strong subtopic similarity link(s)."
    )


def _collect_course_semantic_edges(limit: int = COURSE_SEMANTIC_EDGE_LIMIT) -> list[dict]:
    """
    Aggregate subtopic-level related_subtopics.csv rows into visible course-level
    edges for the frontend graph. This keeps Manara's brain readable while
    preserving the subtopic evidence behind every connection.
    """
    if not RELATED_CSV.exists():
        print("[KG] related_subtopics.csv missing — no course semantic aggregation.")
        return []

    aggregate: dict[tuple[str, str], dict] = {}

    try:
        with open(RELATED_CSV, "r", encoding="utf-8-sig", newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                src_course = str(row.get("source_course", "")).strip()
                tgt_course = str(row.get("target_course", "")).strip()
                if not src_course or not tgt_course or src_course == tgt_course:
                    continue

                try:
                    distance = float(str(row.get("distance", "1")).strip())
                except ValueError:
                    continue
                if distance > SIMILARITY_THRESHOLD:
                    continue

                pair = tuple(sorted([src_course, tgt_course]))
                item = aggregate.setdefault(
                    pair,
                    {
                        "source": pair[0],
                        "target": pair[1],
                        "count": 0,
                        "distance_total": 0.0,
                        "terms": Counter(),
                    },
                )
                item["count"] += 1
                item["distance_total"] += distance

                for key in ("source_topic", "target_topic", "source_subtopic", "target_subtopic"):
                    value = str(row.get(key, "")).strip()
                    if value:
                        item["terms"][value] += 1

    except Exception as exc:
        print(f"[KG] Failed to aggregate course semantic edges: {exc}")
        return []

    edges = []
    for item in aggregate.values():
        if item["count"] < COURSE_SEMANTIC_MIN_LINKS:
            continue
        avg_distance = item["distance_total"] / max(item["count"], 1)
        top_terms = [term for term, _ in item["terms"].most_common(8)]
        relationship = _classify_course_relationship(top_terms)
        strength = min(1.0, (item["count"] / 24.0) * (1.0 - avg_distance))
        edges.append(
            {
                "source_course": item["source"],
                "target_course": item["target"],
                "label": "isSemanticallyRelatedTo",
                "relationship": relationship,
                "strength": round(max(0.12, strength), 3),
                "link_count": int(item["count"]),
                "avg_distance": round(avg_distance, 4),
                "shared_concepts": top_terms[:5],
                "explanation": _edge_explanation(item["source"], item["target"], top_terms, item["count"]),
            }
        )

    edges.sort(key=lambda e: (e["strength"], e["link_count"]), reverse=True)
    print(
        "[KG DEBUG] Course semantic aggregation: "
        f"pairs={len(aggregate)} emitted={min(len(edges), limit)} "
        f"threshold={SIMILARITY_THRESHOLD}"
    )
    return edges[:limit]


def _inject_course_semantic_edges(g: Graph) -> None:
    edges = _collect_course_semantic_edges()
    added = 0
    for edge in edges:
        src_uri = _find_course_uri(g, edge["source_course"]) or make_uri("course", edge["source_course"])
        tgt_uri = _find_course_uri(g, edge["target_course"]) or make_uri("course", edge["target_course"])

        g.add((src_uri, RDF.type, MANARA.Course))
        g.add((tgt_uri, RDF.type, MANARA.Course))
        g.add((src_uri, MANARA.name, Literal(edge["source_course"])))
        g.add((tgt_uri, MANARA.name, Literal(edge["target_course"])))
        g.add((src_uri, RDFS.label, Literal(edge["source_course"])))
        g.add((tgt_uri, RDFS.label, Literal(edge["target_course"])))

        predicate = MANARA.isSemanticallyRelatedTo
        if edge["relationship"] == "mathematical":
            predicate = MANARA.sharesMathematicsWith
        elif edge["relationship"] == "shared_methods":
            predicate = MANARA.sharesMethodsWith

        g.add((src_uri, predicate, tgt_uri))
        g.add((tgt_uri, predicate, src_uri))
        added += 1

    print(f"[KG DEBUG] Added {added} aggregated course semantic edge pair(s).")


def _collect_foundational_edges() -> list[dict]:
    return [dict(edge) for edge in FOUNDATIONAL_RELATIONSHIPS]


def _inject_foundational_course_edges(g: Graph) -> None:
    added = 0
    for edge in _collect_foundational_edges():
        src_uri = _find_course_uri(g, edge["source_course"]) or make_uri("course", edge["source_course"])
        tgt_uri = _find_course_uri(g, edge["target_course"]) or make_uri("course", edge["target_course"])

        g.add((src_uri, RDF.type, MANARA.Course))
        g.add((tgt_uri, RDF.type, MANARA.Course))
        g.add((src_uri, MANARA.name, Literal(edge["source_course"])))
        g.add((tgt_uri, MANARA.name, Literal(edge["target_course"])))
        g.add((src_uri, RDFS.label, Literal(edge["source_course"])))
        g.add((tgt_uri, RDFS.label, Literal(edge["target_course"])))

        predicate = MANARA.isFoundationalFor if edge["label"] == "isFoundationalFor" else MANARA.extendsConceptsFrom
        g.add((src_uri, predicate, tgt_uri))
        added += 1

    print(f"[KG DEBUG] Added {added} explicit foundational course edge(s).")


# =============================================================================
# PREREQUISITE TRAVERSAL (BFS)
# =============================================================================

def get_courses_by_prerequisite_distance(target_course: str) -> list[tuple[str, int]]:
    """
    BFS from target_course along hasPrerequisite edges.

    Returns [(course_name, distance)] sorted by distance ascending.
      distance 1 = direct prerequisite
      distance 2 = prerequisite of prerequisite

    Returns [] if graph not built or course not found.

    Used by api_server.py to:
      - Prioritise diagnostic subtopic sampling from closest prereq courses
      - Sort learning path steps foundationally
    """
    g = _get_graph()
    if g is None:
        return []

    names      = _name_lookup(g)
    target_uri = _find_course_uri(g, target_course)
    if target_uri is None:
        return []

    visited: dict[str, int] = {}
    queue: list[tuple[URIRef, int]] = [(target_uri, 0)]

    while queue:
        current, dist = queue.pop(0)
        for _, _, prereq_uri in g.triples((current, MANARA.hasPrerequisite, None)):
            key = str(prereq_uri)
            if key in visited:
                continue
            visited[key] = dist + 1
            queue.append((prereq_uri, dist + 1))

    result = [
        (names.get(uri, uri.split("/")[-1].replace("_", " ")), dist)
        for uri, dist in visited.items()
    ]
    result.sort(key=lambda x: x[1])
    return result


def get_prerequisite_chain(target_course: str) -> list[str]:
    """Return prerequisite course names in BFS order (closest first)."""
    return [name for name, _ in get_courses_by_prerequisite_distance(target_course)]


def get_subtopics_for_course_via_graph(course_name: str) -> list[dict]:
    """
    Return all subtopics for course_name by traversing the graph:
      Course -> hasTopic -> Topic -> hasSubtopic -> Subtopic

    Returns [{"course_name", "topic_name", "subtopic_name"}, ...]

    Used by api_server.py to drive diagnostic sampling from graph data
    instead of re-reading raw JSON files on every request.
    """
    g = _get_graph()
    if g is None:
        return []

    names      = _name_lookup(g)
    course_uri = _find_course_uri(g, course_name)
    if course_uri is None:
        return []

    results: list[dict] = []
    for _, _, topic_uri in g.triples((course_uri, MANARA.hasTopic, None)):
        topic_name = names.get(str(topic_uri), "")
        if not topic_name:
            continue
        for _, _, sub_uri in g.triples((topic_uri, MANARA.hasSubtopic, None)):
            sub_name = names.get(str(sub_uri), "")
            if not sub_name:
                continue
            results.append({
                "course_name":   course_name,
                "topic_name":    topic_name,
                "subtopic_name": sub_name,
            })

    return results


def get_related_topics_for_course(course_name: str, limit: int = 20) -> list[dict]:
    """
    Return cross-course topics semantically related to topics in course_name.

    Returns [{"source_topic", "target_course", "target_topic"}, ...]

    Used by diagnostic sampling to pull related material from prerequisite
    courses even when topic names differ.
    """
    g = _get_graph()
    if g is None:
        return []

    names      = _name_lookup(g)
    course_uri = _find_course_uri(g, course_name)
    if course_uri is None:
        return []

    results: list[dict] = []
    seen: set[tuple[str, str]] = set()

    for _, _, topic_uri in g.triples((course_uri, MANARA.hasTopic, None)):
        src_name = names.get(str(topic_uri), "")
        for _, _, rel_uri in g.triples((topic_uri, MANARA.isRelatedTo, None)):
            rel_name = names.get(str(rel_uri), "")
            if not rel_name:
                continue
            for owning_uri, _, _ in g.triples((None, MANARA.hasTopic, rel_uri)):
                oc_name = names.get(str(owning_uri), "")
                if oc_name == course_name:
                    continue
                key = (src_name, rel_name)
                if key in seen:
                    continue
                seen.add(key)
                results.append({
                    "source_topic":  src_name,
                    "target_course": oc_name,
                    "target_topic":  rel_name,
                })
                if len(results) >= limit:
                    return results

    return results


# =============================================================================
# SUBTOPIC SEMANTIC QUERY FUNCTIONS
# =============================================================================

def get_semantically_related_subtopics(
    course_name:   str,
    subtopic_name: str,
    limit:         int = 10,
) -> list[dict]:
    """
    Return subtopics from OTHER courses that are semantically similar to the
    given subtopic, via manara:isSemanticallySimilarTo edges.

    Returns [{"target_course", "target_topic", "target_subtopic"}, ...]
    sorted arbitrarily (graph traversal order).

    Returns [] if:
      - graph not built
      - subtopic not found in graph
      - no isSemanticallySimilarTo edges exist (graph not yet rebuilt after
        running related_subtopic_analysis.py with the new subtopic CSV)

    Used by api_server.py to enrich learning path steps with semantically
    related concepts from across the entire curriculum.
    """
    g = _get_graph()
    if g is None:
        return []

    names = _name_lookup(g)

    # Locate the subtopic URI — try (course, subtopic) key first
    sub_uri = EX[f"subtopic/{safe_id(course_name + '_' + subtopic_name)}"]
    if (sub_uri, RDF.type, MANARA.Subtopic) not in g:
        # Fallback: scan all Subtopic nodes matching the name in this course
        sub_uri = None
        course_uri = _find_course_uri(g, course_name)
        if course_uri is None:
            return []
        for _, _, topic_uri in g.triples((course_uri, MANARA.hasTopic, None)):
            for _, _, s_uri in g.triples((topic_uri, MANARA.hasSubtopic, None)):
                if names.get(str(s_uri), "") == subtopic_name:
                    sub_uri = s_uri
                    break
            if sub_uri is not None:
                break
        if sub_uri is None:
            return []

    results: list[dict] = []
    seen:    set[str]   = set()

    for _, _, rel_uri in g.triples((sub_uri, MANARA.isSemanticallySimilarTo, None)):
        rel_name = names.get(str(rel_uri), "")
        if not rel_name or rel_name in seen:
            continue
        seen.add(rel_name)

        # Walk up: rel_uri → Topic → Course
        target_topic  = ""
        target_course = ""
        for topic_uri, _, _ in g.triples((None, MANARA.hasSubtopic, rel_uri)):
            target_topic = names.get(str(topic_uri), "")
            for course_uri, _, _ in g.triples((None, MANARA.hasTopic, topic_uri)):
                target_course = names.get(str(course_uri), "")
                break
            break

        if target_course == course_name:
            continue  # skip same-course edges (should not exist, but guard anyway)

        results.append({
            "target_course":   target_course,
            "target_topic":    target_topic,
            "target_subtopic": rel_name,
        })
        if len(results) >= limit:
            break

    return results


def get_all_subtopics_globally() -> list[dict]:
    """
    Return every subtopic in the graph, across all courses.

    Returns [{"course_name", "topic_name", "subtopic_name"}, ...]

    Useful for:
      - Semantic diversity sampling in diagnostic exam generation
        (pick the most representative subtopics globally)
      - Building a full subtopic catalogue for the UI
      - Verification that graph was built correctly

    Returns [] if graph not built.
    """
    g = _get_graph()
    if g is None:
        return []

    names = _name_lookup(g)
    results: list[dict] = []

    for course_uri, _, _ in g.triples((None, RDF.type, MANARA.Course)):
        course_name = names.get(str(course_uri), "")
        if not course_name:
            continue
        for _, _, topic_uri in g.triples((course_uri, MANARA.hasTopic, None)):
            topic_name = names.get(str(topic_uri), "")
            if not topic_name:
                continue
            for _, _, sub_uri in g.triples((topic_uri, MANARA.hasSubtopic, None)):
                sub_name = names.get(str(sub_uri), "")
                if not sub_name:
                    continue
                results.append({
                    "course_name":   course_name,
                    "topic_name":    topic_name,
                    "subtopic_name": sub_name,
                })

    return results


# =============================================================================
# FRONTEND PAYLOAD
# =============================================================================

def load_graph_for_frontend() -> dict:
    """
    Return a size-capped, frontend-ready payload for InsideManarasBrainPage.

    {
      "nodes":      [...],
      "edges":      [...],
      "is_real":    True | False,
      "node_count": int,
      "edge_count": int,
      "error":      str | None   # present only when is_real=False
    }

    Improvements over the original:
    - Graph read from MODULE-LEVEL CACHE — no disk I/O on repeated requests.
    - Labels come from stored manara:name triples — no URI-slug garbling.
    - Descriptions are meaningful (course code + prereqs for courses).
    - Payload is SERVER-SIDE capped at FRONTEND_MAX_* constants.
    - Returns is_real=False with a clear error when the graph is not built.
      NO fake/demo data is injected.
    - isRelatedTo edges included for cross-course semantic visualization.
    """
    g = _get_graph()
    if g is None:
        return {
            "nodes":   [],
            "edges":   [],
            "is_real": False,
            "error": (
                "Knowledge graph has not been built yet. "
                "Run: python knowledgegraph.py"
            ),
        }

    names = _name_lookup(g)
    desc  = _course_desc_lookup(g, names)

    all_course_uris = [str(subj) for subj, _, _ in g.triples((None, RDF.type, MANARA.Course))]
    course_uri_by_name = {
        names.get(uri, uri.split("/")[-1].replace("_", " ").title()).strip().casefold(): uri
        for uri in all_course_uris
    }

    def _course_uri(course_name: str) -> str:
        key = str(course_name).strip().casefold()
        return course_uri_by_name.get(key, str(make_uri("course", course_name)))

    def _edge_priority(edge: dict) -> tuple[float, int, float]:
        strength = float(edge.get("strength", 0.0) or 0.0)
        link_count = int(edge.get("link_count", 0) or 0)
        avg_distance = float(edge.get("avg_distance", 1.0) or 1.0)
        relationship_boost = {
            "foundational": 1.25,
            "mathematical": 1.12,
            "shared_methods": 1.08,
            "semantic": 1.0,
            "prerequisite": 0.9,
            "hierarchy": 0.2,
        }.get(str(edge.get("relationship", "semantic")), 1.0)
        return (strength * relationship_boost, link_count, 1.0 - avg_distance)

    # Semantic candidate edges are the primary visualization spine. They are
    # already aggregated from subtopic density, so subtopic intelligence drives
    # which course relationships survive the final trim.
    course_semantic_edges = sorted(
        _collect_course_semantic_edges(COURSE_SEMANTIC_EDGE_LIMIT),
        key=_edge_priority,
        reverse=True,
    )
    foundational_edges = _collect_foundational_edges()

    edge_candidates: list[dict] = []
    for edge in foundational_edges + course_semantic_edges:
        src_uri = _course_uri(edge["source_course"])
        tgt_uri = _course_uri(edge["target_course"])
        edge_candidates.append(
            {
                "source_uri": src_uri,
                "target_uri": tgt_uri,
                "source": src_uri.replace(BASE_URI, ""),
                "target": tgt_uri.replace(BASE_URI, ""),
                "label": edge.get("label", "isSemanticallyRelatedTo"),
                "relationship": edge.get("relationship", "semantic"),
                "strength": edge.get("strength", 0.5),
                "link_count": edge.get("link_count", 0),
                "avg_distance": edge.get("avg_distance", 1.0),
                "shared_concepts": edge.get("shared_concepts", []),
                "explanation": edge.get("explanation", "Connected by Manara's semantic knowledge graph."),
            }
        )

    edge_candidates.sort(key=_edge_priority, reverse=True)

    # Selection is relationship-first:
    #   1. seed from strongest semantic/foundational edges
    #   2. recursively include strong neighbors
    #   3. include endpoints before final edge trimming
    selected_nodes: set[str] = set()
    node_scores: Counter[str] = Counter()
    adjacency: dict[str, list[dict]] = defaultdict(list)

    for edge in edge_candidates:
        src = edge["source_uri"]
        tgt = edge["target_uri"]
        adjacency[src].append(edge)
        adjacency[tgt].append(edge)
        score = _edge_priority(edge)[0] + min(2.5, int(edge.get("link_count", 0) or 0) / 80)
        node_scores[src] += score
        node_scores[tgt] += score

    for edge in edge_candidates:
        if len(selected_nodes) >= FRONTEND_MAX_COURSE_NODES:
            break
        selected_nodes.add(edge["source_uri"])
        selected_nodes.add(edge["target_uri"])

    for _ in range(2):
        expanded = False
        for node_uri in list(selected_nodes):
            strong_neighbors = sorted(
                adjacency.get(node_uri, []),
                key=_edge_priority,
                reverse=True,
            )
            for edge in strong_neighbors[:8]:
                other = edge["target_uri"] if edge["source_uri"] == node_uri else edge["source_uri"]
                if other in selected_nodes:
                    continue
                if (
                    float(edge.get("strength", 0) or 0) >= 0.55
                    or int(edge.get("link_count", 0) or 0) >= 5
                    or edge.get("relationship") == "foundational"
                ):
                    selected_nodes.add(other)
                    expanded = True
                if len(selected_nodes) >= FRONTEND_MAX_COURSE_NODES:
                    break
            if len(selected_nodes) >= FRONTEND_MAX_COURSE_NODES:
                break
        if not expanded:
            break

    if len(selected_nodes) < FRONTEND_MAX_COURSE_NODES:
        for uri, _ in node_scores.most_common(FRONTEND_MAX_COURSE_NODES):
            selected_nodes.add(uri)
            if len(selected_nodes) >= FRONTEND_MAX_COURSE_NODES:
                break

    # Add a small, scored topic context after the course semantic skeleton is
    # fixed. This preserves curriculum structure without letting topic order
    # destroy course-to-course connectivity.
    selected_topics: set[str] = set()
    topic_scores: Counter[str] = Counter()
    for course_uri in selected_nodes:
        for _, _, topic_uri in g.triples((URIRef(course_uri), MANARA.hasTopic, None)):
            topic_scores[str(topic_uri)] += max(node_scores.get(course_uri, 1), 1)

    for topic_uri, _ in topic_scores.most_common(FRONTEND_MAX_TOPIC_NODES):
        selected_topics.add(topic_uri)

    all_selected = set(selected_nodes) | selected_topics

    nodes: list[dict] = []
    added_nodes: set[str] = set()

    def _make_node(uri_str: str) -> Optional[dict]:
        node_id = uri_str.replace(BASE_URI, "")
        node_type = _detect_node_type(node_id)
        if node_type == "hidden":
            return None
        label = names.get(uri_str)
        if not label:
            raw = node_id.split("/")[-1]
            raw = re.sub(r"_\d+$", "", raw)
            label = raw.replace("_", " ").title()
        label = str(label).strip()
        node_desc = desc.get(uri_str, label) if node_type == "course" else label
        return {
            "id": node_id,
            "label": label,
            "display_label": label,
            "type": node_type,
            "desc": node_desc,
            "score": round(float(node_scores.get(uri_str, topic_scores.get(uri_str, 0))), 3),
        }

    def _ensure_node(uri_str: str) -> None:
        if uri_str in added_nodes:
            return
        n = _make_node(uri_str)
        if n:
            nodes.append(n)
            added_nodes.add(uri_str)

    for uri_str in sorted(all_selected, key=lambda u: node_scores.get(u, topic_scores.get(u, 0)), reverse=True):
        _ensure_node(uri_str)

    edge_keys: set[tuple[str, str, str]] = set()
    candidate_edges: list[dict] = []

    def _add_candidate(edge: dict) -> None:
        key = (str(edge.get("source")), str(edge.get("target")), str(edge.get("label", "")))
        rev_key = (key[1], key[0], key[2])
        if key in edge_keys or rev_key in edge_keys:
            return
        edge_keys.add(key)
        candidate_edges.append(edge)

    # Always include selected semantic/foundational endpoints before trimming.
    for edge in edge_candidates:
        if edge["source_uri"] not in all_selected and edge["target_uri"] not in all_selected:
            continue
        if edge["source_uri"] not in all_selected and len(selected_nodes) < FRONTEND_MAX_COURSE_NODES:
            selected_nodes.add(edge["source_uri"])
            all_selected.add(edge["source_uri"])
            _ensure_node(edge["source_uri"])
        if edge["target_uri"] not in all_selected and len(selected_nodes) < FRONTEND_MAX_COURSE_NODES:
            selected_nodes.add(edge["target_uri"])
            all_selected.add(edge["target_uri"])
            _ensure_node(edge["target_uri"])
        if edge["source_uri"] in all_selected and edge["target_uri"] in all_selected:
            _add_candidate({k: v for k, v in edge.items() if not k.endswith("_uri")})

    relationship_map = {
        "hasPrerequisite": "prerequisite",
        "hasConcurrent": "prerequisite",
        "hasTopic": "hierarchy",
        "hasSubtopic": "hierarchy",
        "isRelatedTo": "semantic",
        "isSemanticallySimilarTo": "semantic",
        "isSemanticallyRelatedTo": "semantic",
        "sharesMathematicsWith": "mathematical",
        "sharesMethodsWith": "shared_methods",
        "isFoundationalFor": "foundational",
        "extendsConceptsFrom": "foundational",
    }
    allowed = set(relationship_map)

    rdf_edges_seen = 0
    endpoint_expansions = 0
    for subj, pred, obj in g:
        if not isinstance(obj, URIRef):
            continue
        pred_name = str(pred).split("/")[-1]
        if pred_name not in allowed:
            continue

        subj_str = str(subj)
        obj_str = str(obj)
        relationship = relationship_map[pred_name]

        if subj_str not in all_selected or obj_str not in all_selected:
            important = relationship in {"semantic", "mathematical", "shared_methods", "foundational", "prerequisite"}
            if not important:
                continue

            # Fix the old aggressive endpoint filter: important relationships
            # can pull in their missing endpoint while we still have capacity.
            if subj_str in all_selected and obj_str not in all_selected and _detect_node_type(obj_str.replace(BASE_URI, "")) == "course":
                if len(selected_nodes) < FRONTEND_MAX_COURSE_NODES:
                    selected_nodes.add(obj_str)
                    all_selected.add(obj_str)
                    _ensure_node(obj_str)
                    endpoint_expansions += 1
                else:
                    continue
            elif obj_str in all_selected and subj_str not in all_selected and _detect_node_type(subj_str.replace(BASE_URI, "")) == "course":
                if len(selected_nodes) < FRONTEND_MAX_COURSE_NODES:
                    selected_nodes.add(subj_str)
                    all_selected.add(subj_str)
                    _ensure_node(subj_str)
                    endpoint_expansions += 1
                else:
                    continue
            else:
                continue

        subj_id = subj_str.replace(BASE_URI, "")
        obj_id = obj_str.replace(BASE_URI, "")
        if _detect_node_type(subj_id) == "hidden" or _detect_node_type(obj_id) == "hidden":
            continue

        _ensure_node(subj_str)
        _ensure_node(obj_str)
        rdf_edges_seen += 1
        base_strength = {
            "foundational": 0.95,
            "prerequisite": 0.8,
            "semantic": 0.55,
            "mathematical": 0.65,
            "shared_methods": 0.65,
            "hierarchy": 0.25,
        }.get(relationship, 0.4)
        _add_candidate(
            {
                "source": subj_id,
                "target": obj_id,
                "label": pred_name,
                "relationship": relationship,
                "strength": base_strength,
                "link_count": 0,
                "shared_concepts": [],
                "explanation": f"Connected by graph relationship: {pred_name}.",
            }
        )

    candidate_edges.sort(key=_edge_priority, reverse=True)
    edges = candidate_edges[:FRONTEND_MAX_EDGES]

    relationship_counts = Counter(str(e.get("relationship", "unknown")) for e in edges)
    semantic_edges_generated = sum(
        1 for e in edges
        if e.get("relationship") in {"semantic", "mathematical", "shared_methods"}
    )
    filtered_edges = max(0, len(candidate_edges) - len(edges))

    print(
        "[KG DEBUG] Frontend graph payload: "
        f"nodes={len(nodes)} edges={len(edges)} candidates={len(candidate_edges)} "
        f"semantic_edges={semantic_edges_generated} endpoint_expansions={endpoint_expansions} "
        f"rdf_edges_seen={rdf_edges_seen} relationship_counts={dict(relationship_counts)}"
    )
    return {
        "nodes": nodes,
        "edges": edges,
        "is_real": True,
        "node_count": len(nodes),
        "edge_count": len(edges),
        "debug": {
            "candidate_edges_count": len(candidate_edges),
            "semantic_edges_generated": semantic_edges_generated,
            "relationship_counts": dict(relationship_counts),
            "rendered_edges_count": len(edges),
            "filtered_edges_count": filtered_edges,
            "endpoint_expansions": endpoint_expansions,
            "rdf_edges_seen": rdf_edges_seen,
            "selection_strategy": "semantic_expand_then_trim",
        },
    }


# =============================================================================
# GRAPH STATUS
# =============================================================================

def graph_status() -> dict:
    """Return a health/status dict for /api/graph/status."""
    if not OUTPUT_FILE.exists():
        return {
            "built":       False,
            "path":        str(OUTPUT_FILE),
            "triple_count": 0,
            "message":     "Graph not built. Run `python knowledgegraph.py`.",
        }

    g = _get_graph()
    if g is None:
        return {
            "built":       False,
            "path":        str(OUTPUT_FILE),
            "triple_count": 0,
            "message":     "Graph file exists but could not be parsed.",
        }

    import datetime
    mtime    = OUTPUT_FILE.stat().st_mtime
    built_at = datetime.datetime.fromtimestamp(mtime).strftime("%Y-%m-%d %H:%M:%S")

    semantic_subtopic_edges = sum(
        1 for _ in g.triples((None, MANARA.isSemanticallySimilarTo, None))
    ) // 2
    legacy_topic_edges = sum(
        1 for _ in g.triples((None, MANARA.isRelatedTo, None))
    ) // 2
    course_semantic_edges = (
        sum(1 for _ in g.triples((None, MANARA.isSemanticallyRelatedTo, None)))
        + sum(1 for _ in g.triples((None, MANARA.sharesMathematicsWith, None)))
        + sum(1 for _ in g.triples((None, MANARA.sharesMethodsWith, None)))
    ) // 2
    foundational_edges = (
        sum(1 for _ in g.triples((None, MANARA.isFoundationalFor, None)))
        + sum(1 for _ in g.triples((None, MANARA.extendsConceptsFrom, None)))
    )

    return {
        "built":                        True,
        "path":                         str(OUTPUT_FILE),
        "triple_count":                 len(g),
        "courses":                      sum(1 for _ in g.triples((None, RDF.type, MANARA.Course))),
        "topics":                       sum(1 for _ in g.triples((None, RDF.type, MANARA.Topic))),
        "subtopics":                    sum(1 for _ in g.triples((None, RDF.type, MANARA.Subtopic))),
        "semantic_subtopic_edges":      semantic_subtopic_edges,
        "legacy_topic_edges":           legacy_topic_edges,
        "course_semantic_edges":        course_semantic_edges,
        "foundational_edges":           foundational_edges,
        "cross_course_edges":           semantic_subtopic_edges + legacy_topic_edges + course_semantic_edges + foundational_edges,
        "built_at":                     built_at,
        "message":                      "Graph is loaded and ready.",
    }


# =============================================================================
# ENTRY POINT
# =============================================================================

def main() -> None:
    print("=" * 60)
    print("Manara Knowledge Graph Builder")
    print("=" * 60)

    if not COURSES_DIR.exists():
        print(f"ERROR: Courses directory not found: {COURSES_DIR}")
        return

    print(f"Courses directory : {COURSES_DIR}")
    print(f"Output file       : {OUTPUT_FILE}")
    print(f"Related CSV       : {RELATED_CSV}")
    print()

    g = build_knowledge_graph(COURSES_DIR)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    g.serialize(destination=str(OUTPUT_FILE), format="turtle")
    invalidate_graph_cache()

    names = _name_lookup(g)

    semantic_sub_edges = sum(
        1 for _ in g.triples((None, MANARA.isSemanticallySimilarTo, None))
    ) // 2
    legacy_topic_edges = sum(
        1 for _ in g.triples((None, MANARA.isRelatedTo, None))
    ) // 2
    course_semantic_edges = (
        sum(1 for _ in g.triples((None, MANARA.isSemanticallyRelatedTo, None)))
        + sum(1 for _ in g.triples((None, MANARA.sharesMathematicsWith, None)))
        + sum(1 for _ in g.triples((None, MANARA.sharesMethodsWith, None)))
    ) // 2
    foundational_edges = (
        sum(1 for _ in g.triples((None, MANARA.isFoundationalFor, None)))
        + sum(1 for _ in g.triples((None, MANARA.extendsConceptsFrom, None)))
    )

    print()
    print("Graph built successfully.")
    print(f"  Total triples                   : {len(g)}")
    print(f"  Courses                         : {sum(1 for _ in g.triples((None, RDF.type, MANARA.Course)))}")
    print(f"  Topics                          : {sum(1 for _ in g.triples((None, RDF.type, MANARA.Topic)))}")
    print(f"  Subtopics                       : {sum(1 for _ in g.triples((None, RDF.type, MANARA.Subtopic)))}")
    print(f"  isSemanticallySimilarTo edges   : {semantic_sub_edges}")
    print(f"  isRelatedTo (legacy) edges      : {legacy_topic_edges}")
    print(f"  aggregated course semantic edges: {course_semantic_edges}")
    print(f"  foundational course edges       : {foundational_edges}")
    print(f"  Output                          : {OUTPUT_FILE}")

    print("\nCourse nodes:")
    for subj, _, _ in g.triples((None, RDF.type, MANARA.Course)):
        print(f"  {str(subj).replace(BASE_URI, '')}  ->  \"{names.get(str(subj), '?')}\"")

    print("\nSample topic labels (first 5):")
    for i, (subj, _, _) in enumerate(g.triples((None, RDF.type, MANARA.Topic))):
        if i >= 5:
            break
        print(f"  {str(subj).replace(BASE_URI, '')}  ->  \"{names.get(str(subj), '?')}\"")


if __name__ == "__main__":
    main()
